### ISSUE TITLE
Support KRM in Kustomize plugins

### ISSUE THREAD

**Issue by aabouzaid** [DevOpsHiveNet/devops-coding-mentorship#5]
### Intro

[Kustomize](https://kustomize.io/) (the official tool to create K8s IaC) adopted the new Kubernetes declarative configurations known as `KRM Functions`. The new style is used as a unified way to interact with Kustomize plugins. There are 2 ways to use KRM in the plugins: [Containerized KRM Functions](https://kubectl.docs.kubernetes.io/guides/extending_kustomize/containerized_krm_functions/) and [Exec KRM functions](https://kubectl.docs.kubernetes.io/guides/extending_kustomize/exec_krm_functions/).

### Acquired Skills

By doing any of the tasks in this epic, you will gain the following skills:
- Golang coding skills.
- Kustomize plugin ecosystem.
- Unerstanding of [Kubernetes Resource Model](https://github.com/kubernetes/design-proposals-archive/blob/main/architecture/resource-management.md) (KRM).

### The Challange

Support [KRM](https://github.com/kubernetes-sigs/kustomize/blob/master/cmd/config/docs/api-conventions/functions-spec.md) in Kustomize plugins that don't support it yet.

### The Tasks

Check [Awesome Kustomize](https://github.com/aabouzaid/awesome-kustomize/#plugins) to find the plugins that don't support KRM yet. 
The following are the open tasks already.

- [ ] https://github.com/aabouzaid/devops-coding-mentorship/issues/6
- [ ] https://github.com/aabouzaid/devops-coding-mentorship/issues/7
- [ ] https://github.com/aabouzaid/devops-coding-mentorship/issues/2
